### ISSUE TITLE
creates but does not insert images with TB 52.1.0

### ISSUE THREAD

**Issue by lashkevi** [protz/LatexIt#19]
With TB 52.1.0 LaTeX It! creates images (I can see the log), but does not insert them into the text (blank spaces instead).

**Comment by marmistrz** [comment]
This is due to a change in Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1362237

**Comment by theodore-norvell** [comment]
I have a similar problem.  Thunderbird gives a prompt at the bottom of the screen "Thunderbird has blocked some files from loading into this message. Unblocking the file will include it in the message." Each file can be unblocked one.  But this is tedious.  There is discussion at http://forums.mozillazine.org/viewtopic.php?f=39&t=3029707 and  forums.mozillazine.org/viewtopic.php?f=39&t=3029842 . Apparently if LatexIt were to use "data:" URIs instead of "file:" URIs, the problem would go away.

**Comment by protz** [comment]
Hey, any chance you could submit a patch for that? I'd happily review it.

**Comment by sphh** [comment]
I would love to submit a patch for this issue, because I use LatexIt nearly every day. Unfortunately my knowledge of JavaScript is very, very limited (and of TB extensions even more so). I did a quick search how to convert a picture into a data URI as requested by TB nowadays:

- https://davidwalsh.name/convert-image-data-uri-javascript
- https://stackoverflow.com/questions/23808563/js-how-to-encode-an-image-png-into-base64-code-for-data-uri-embedding#answer-26595628
- https://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript#answer-20285053

These should solve the problem of converting the picture into the data URI. Can I simply replace the "file://" URI in the returns of run_latex() (lines 106 and 252 in main.js) with this data URI?

**Comment by theodore-norvell** [comment]
I looked into it, but didn't have time to do it.  It doesn't look that hard if you use the right interfaces.  I think you create a FileObject which is a sort of a Blob and then turn the FileObject/Blob into a data URI.

Why not give it a shot?

Cheers,
Theodore Norvell

**Comment by sphh** [comment]
Hi Theodore,
I gave it a shot and replaced the two lines with:
Line 106:
```javascript
//        return [0, "file://"+g_image_cache[latex_expr], log+"Image was already generated\n"];
        var reader = new FileReader();
        return [0, reader.readAsDataURL(g_image_cache[latex_expr]), log+"Image was already generated\n"];
```
Line 252:
```javascript
//      return [st, "file://"+png_file.path, log];
      var reader = new FileReader();
      return [st, reader.readAsDataURL(png_file.path), log+"Image was already generated\n"];
```
But got this error message:
```
TypeError: Argument 1 of FileReader.readAsDataURL is not an object.
run_latex@chrome://tblatex/content/main.js:256:19
replace_latex_nodes/<@chrome://tblatex/content/main.js:334:28
replace_latex_nodes@chrome://tblatex/content/main.js:329:45
tblatex.on_latexit@chrome://tblatex/content/main.js:374:7
oncommand@chrome://messenger/content/messengercompose/messengercompose.xul:1:1
```
which does even make sense to me, because the ``.path`` is not the object expected. So I replaced ``png_file.path`` with ``png_file``, but got another error message:
```TypeError: Argument 1 of FileReader.readAsDataURL does not implement interface Blob.
run_latex@chrome://tblatex/content/main.js:256:19
replace_latex_nodes/<@chrome://tblatex/content/main.js:334:28
replace_latex_nodes@chrome://tblatex/content/main.js:329:45
tblatex.on_latexit@chrome://tblatex/content/main.js:374:7
oncommand@chrome://messenger/content/messengercompose/messengercompose.xul:1:1
```

That is as far as my knowledge of JavaScript let me go... Sorry.

**Comment by theodore-norvell** [comment]
The argument to reader.readAsDataURL should be a File object. Something like this should work


       var reader = new FileReader();
       var file = File.createFromFileName( png_file.path );
       var uri = reader.readAsDataURL( file );
       return [st, uri, log+"Image was already generated\n"];


See https://developer.mozilla.org/en-US/docs/Extensions/Using_the_DOM_File_API_in_chrome_code

and https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

Theo

**Comment by sphh** [comment]
Thank you for the pointers. I finally managed to get it working.

```diff
--- content/main.js
+++ content/main.js
@@ -103,7 +103,7 @@
       if (g_image_cache[latex_expr]) {
         if (debug)
           log += "Found a cached image file "+g_image_cache[latex_expr]+", returning\n";
-        return [0, "file://"+g_image_cache[latex_expr], log+"Image was already generated\n"];
+        return [0, g_image_cache[latex_expr], log+"Image was already generated\n"];
       }
 
       var init_file = function(path) {
@@ -249,7 +249,7 @@
       //  in case of error.
       temp_file.remove(false);
 
-      return [st, "file://"+png_file.path, log];
+      return [st, png_file.path, log];
     } catch (e) {
       dump(e+"\n");
       dump(e.stack+"\n");
@@ -334,9 +334,16 @@
         if (debug)
           write_log("--> Replacing node... ");
         var img = editor.createElementWithDefaults("img");
-        img.setAttribute("alt", elt.nodeValue);
-        img.setAttribute("src", url);
-        img.setAttribute("style", "vertical-align: middle");
+        var reader = new FileReader();
+        var file = File.createFromFileName(url);
+
+        reader.addEventListener("load", function() {
+          img.alt = elt.nodeValue;
+          img.style = "vertical-align: middle";
+          img.src = reader.result;
+        }, false);
+        reader.readAsDataURL(file);
+
         elt.parentNode.insertBefore(img, elt);
         elt.parentNode.removeChild(elt);
         push_undo_func(function () {
@@ -419,10 +426,17 @@
         write_log(log);
         if (st == 0 || st == 1) {
           var img = editor.createElementWithDefaults("img");
-          img.setAttribute("alt", latex_expr);
-          img.setAttribute("title", latex_expr);
-          img.setAttribute("src", url);
-          img.setAttribute("style", "vertical-align: middle");
+          var reader = new FileReader();
+          var file = File.createFromFileName(url);
+
+          reader.addEventListener("load", function() {
+            img.alt = latex_expr;
+            img.title = latex_expr;
+            img.style = "vertical-align: middle";
+            img.src = reader.result;
+          }, false);
+          reader.readAsDataURL(file);
+
           editor.insertElementAtSelection(img, true);
           push_undo_func(function () {
             img.parentNode.removeChild(img);
```

@protz : Do you want to include this patch in your next release?

**Comment by protz** [comment]
absolutely, this is amazing! can you submit a pull request? thanks much!!

**Comment by protz** [comment]
version has been submitted to addons.mozilla.org

**Comment by sphh** [comment]
Thanks for applying this patch. I only learned last week how to do a pull request, but you were faster!!
