### ISSUE TITLE
LaTeX It! don't complile my formulas

### ISSUE THREAD

**Issue by AmadoCab** [protz/LatexIt#55]
The wiki says that to use LaTeX It! In MacOS we have to open Thunderbird from Terminal:

`/Applications/Thunderbird.app/Contents/MacOS/thunderbird-bin`

Then we have to go to Tools, then to Add-ons, after that we go to Latex It! and finally to Preferences. My problem is that I can't find the Preferences of the Add-ons. Even when I go to "Add-on preferences" it just says: "No Add-on settings found." So I don't know what to do. :c

**Comment by sphh** [comment]
Sorry to hear that it is not working. Can you please tell us the following:
Thunderbird version
LaTeX It! version
MacOS version
and the messages from the console concerning `LaTeX It!`

BTW the preferences moved from `Tools > ...` to `Add-ons >` (at least with my version of `LaTeX It!`). Looks like the Wiki is out-of date, but you found it already!

**Comment by AmadoCab** [comment]
Thanks @sphh , my version of Thunderbird:68.9.0, LaTeX It!:0.6.8 and MacOS:10.13.6

The message from LaTeX It! is
![problema](https://user-images.githubusercontent.com/28881001/84688834-3ce7bb00-aefd-11ea-9a7a-c4becfed83e6.png)
Possible reasons include: you didn't setup the paths properly in the addon's options.
Wrong path for latex bin. Please set the right path in the options dialog first.
(The complete text)

And in Terminal I have no message  from LaTeX It!

**Comment by sphh** [comment]
Now I am flying blind, because I neither work on MacOS nor do I have LaTeX It! 0.6.8 installed. I am already at version 0.7.1 ;-)

Thunderbird has changed the place in the GUI where they put the configurations... But if I remember correctly, the LaTeX It! button has a drop-down menu attached and the last item in this menu is the configuration menu. Does that work?

If not, I can dig out my version, which already includes all open pull requests. Perhaps that works better. Who knows? But if you are adventurous, you make the extension yourself: It requires a tiny bit of terminal work, but nothing fancy: Clone the repository/Download the files, apply the pull requests #53 (and #54 if you like it) and type `make` and you will be rewarded with an installable `.xpi` file.

**Comment by AmadoCab** [comment]
You remember well, the last button on the menu is Options, and it display this menu:
![pat](https://user-images.githubusercontent.com/28881001/84720830-607e2600-af3c-11ea-9aef-56a2de3dd624.png)

What can I do here to correct the problem? 😿  sorry, I'm not really good on this.

**Comment by sphh** [comment]
Clicking on `Open the autodetection dialog` should bring you to a new window which auto-detects the latex and dvipng executable. If that does not work, put these two paths ` /Library/TeX/texbin/latex` and ` /Library/TeX/texbin/dvipng` into the fields for the `latex` and `dvipng` executables (as mentioned in the [wiki](https://github.com/protz/LatexIt/wiki/Latexit-and-macos)). You can use the `Browse` button, if you like.

You have LaTeX installed on your computer, haven't you?

**Comment by AmadoCab** [comment]
Thank you for your help. Yes I have installed LaTeX on my computer and `autodetection dialog` works, now everything is fine.  😸

**Comment by sphh** [comment]
Glad that it works now!
