### ISSUE TITLE
LaTeX It! requiring full access.

### ISSUE THREAD

**Issue by Etturaz** [protz/LatexIt#85]
Hello.
My question is: why is that LaTeX It! for TB 78+(i.e. the [pre-release file](https://github.com/protz/LatexIt/issues/61#issuecomment-811745189)) requires "_full, unrestricted access to Thunderbird, and your computer_"?

Thanks. Have a great day y' all!

**Comment by sphh** [comment]
I believe, it's because of this "[glue code](https://github.com/thundernest/addon-developer-support)" used to make it available as a mailextension add-on. I am sure, @jobisoft can shed more light on it.

**Comment by jobisoft** [comment]
You guys are pretty up the fence because of that. What if I tell you that ALL add-ons before TB78 had FULL ACCESS without telling you that? It was implicit. No one cared.

Have you clicked on the "learn more about permissions" link in the very same window? You should do that.

After TB78 we introduced the permission system and more and more add-ons convert to the new system, but some of them still need stuff, that is not provided by the new system (the WebExtension system), so they have to use the legacy approach and that again allows to do everything.

**Comment by jobisoft** [comment]
My answer may have been a bit harsh. But I just do not get this attitude. Users are unhappy with the big add-on fallout after TB78 and developers like sphh work very hard to get everything working again and then user still complain. That is unfair. 

Thunderbird provides all the information users need to understand this but they are faster complaining than reading the description.

I may be misjudging Etturaz and his intention may have been to actually see the code which needs those permissions, but I get this way to often and developers are negatively impacted by this attitude.

**Comment by sphh** [comment]
Actually it is @jobisoft who is doing all the hard work!!

I can absolutely understand this reaction: Too many questions about an obvious thing … Because there is not only the link when installing an add-on (but to be honest, who ever reads lengthy explanations, like T&Cs, EULAs or the German AGBs when installing some piece of software? I personally don't do it (very often) …), but also a link is provided in the add-ons `Permission` page as well, which can be read at your leisure. (Good thinking to put it there as well!)

Unfortunately this page also says for LatexIt!: "This extension doesn't require any permissions". @jobisoft: Is there a way to change that?

**Comment by jobisoft** [comment]
> Unfortunately this page also says for LatexIt!: "This extension doesn't require any permissions". @jobisoft: Is there a way to change that?

I did! In one of the latest updates of Thunderbrid I slipped in a patch for that:

![image](https://user-images.githubusercontent.com/5830621/115210718-2b63d680-a0ff-11eb-8ce3-1e07e90ade8b.png)

**Comment by sphh** [comment]
Great @jobisoft.

@Etturaz, I hope this answers your question. If not, please get into contact/reopen this issue.
